# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/ExportedDataDao/ExportedDataDaoV2.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from proto import FeedStateDao_pb2 as proto_dot_FeedStateDao__pb2
from proto.ProgramBlueprintDao import ProgramBlueprintDaoV1_pb2 as proto_dot_ProgramBlueprintDao_dot_ProgramBlueprintDaoV1__pb2
from proto.SessionBlueprintDao import SessionBlueprintDaoV2_pb2 as proto_dot_SessionBlueprintDao_dot_SessionBlueprintDaoV2__pb2
from proto.SessionHistoryDao import SessionHistoryDaoV2_pb2 as proto_dot_SessionHistoryDao_dot_SessionHistoryDaoV2__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-proto/ExportedDataDao/ExportedDataDaoV2.proto\x12!LiftLog.Ui.Models.ExportedDataDao\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x18proto/FeedStateDao.proto\x1a\x35proto/ProgramBlueprintDao/ProgramBlueprintDaoV1.proto\x1a\x35proto/SessionBlueprintDao/SessionBlueprintDaoV2.proto\x1a\x31proto/SessionHistoryDao/SessionHistoryDaoV2.proto\"\xec\x03\n\x11\x45xportedDataDaoV2\x12\x43\n\x08sessions\x18\x01 \x03(\x0b\x32\x31.LiftLog.Ui.Models.SessionHistoryDao.SessionDaoV2\x12M\n\x07program\x18\x02 \x03(\x0b\x32<.LiftLog.Ui.Models.SessionBlueprintDao.SessionBlueprintDaoV2\x12_\n\x0esaved_programs\x18\x03 \x03(\x0b\x32G.LiftLog.Ui.Models.ExportedDataDao.ExportedDataDaoV2.SavedProgramsEntry\x12\x37\n\x11\x61\x63tive_program_id\x18\x04 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x35\n\nfeed_state\x18\x05 \x01(\x0b\x32!.LiftLog.Ui.Models.FeedStateDaoV1\x1ar\n\x12SavedProgramsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12K\n\x05value\x18\x02 \x01(\x0b\x32<.LiftLog.Ui.Models.ProgramBlueprintDao.ProgramBlueprintDaoV1:\x02\x38\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.ExportedDataDao.ExportedDataDaoV2_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EXPORTEDDATADAOV2_SAVEDPROGRAMSENTRY._options = None
  _EXPORTEDDATADAOV2_SAVEDPROGRAMSENTRY._serialized_options = b'8\001'
  _EXPORTEDDATADAOV2._serialized_start=304
  _EXPORTEDDATADAOV2._serialized_end=796
  _EXPORTEDDATADAOV2_SAVEDPROGRAMSENTRY._serialized_start=682
  _EXPORTEDDATADAOV2_SAVEDPROGRAMSENTRY._serialized_end=796
# @@protoc_insertion_point(module_scope)
