# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/ProgramBlueprintDao/ProgramBlueprintDaoV1.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from proto.SessionBlueprintDao import SessionBlueprintDaoV2_pb2 as proto_dot_SessionBlueprintDao_dot_SessionBlueprintDaoV2__pb2
from proto import Utils_pb2 as proto_dot_Utils__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5proto/ProgramBlueprintDao/ProgramBlueprintDaoV1.proto\x12%LiftLog.Ui.Models.ProgramBlueprintDao\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x35proto/SessionBlueprintDao/SessionBlueprintDaoV2.proto\x1a\x11proto/Utils.proto\"\xe6\x02\n\x1eProgramBlueprintDaoContainerV1\x12x\n\x12program_blueprints\x18\x01 \x03(\x0b\x32\\.LiftLog.Ui.Models.ProgramBlueprintDao.ProgramBlueprintDaoContainerV1.ProgramBlueprintsEntry\x12<\n\x11\x61\x63tive_program_id\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValueH\x00\x88\x01\x01\x1av\n\x16ProgramBlueprintsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12K\n\x05value\x18\x02 \x01(\x0b\x32<.LiftLog.Ui.Models.ProgramBlueprintDao.ProgramBlueprintDaoV1:\x02\x38\x01\x42\x14\n\x12_active_program_id\"\xd1\x01\n\x15ProgramBlueprintDaoV1\x12\x0c\n\x04name\x18\x01 \x01(\t\x12N\n\x08sessions\x18\x05 \x03(\x0b\x32<.LiftLog.Ui.Models.SessionBlueprintDao.SessionBlueprintDaoV2\x12\x38\n\x0blast_edited\x18\x06 \x01(\x0b\x32\x1e.LiftLog.Ui.Models.DateOnlyDaoH\x00\x88\x01\x01\x42\x0e\n\x0c_last_editedJ\x04\x08\x02\x10\x03J\x04\x08\x03\x10\x04J\x04\x08\x04\x10\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.ProgramBlueprintDao.ProgramBlueprintDaoV1_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROGRAMBLUEPRINTDAOCONTAINERV1_PROGRAMBLUEPRINTSENTRY._options = None
  _PROGRAMBLUEPRINTDAOCONTAINERV1_PROGRAMBLUEPRINTSENTRY._serialized_options = b'8\001'
  _PROGRAMBLUEPRINTDAOCONTAINERV1._serialized_start=203
  _PROGRAMBLUEPRINTDAOCONTAINERV1._serialized_end=561
  _PROGRAMBLUEPRINTDAOCONTAINERV1_PROGRAMBLUEPRINTSENTRY._serialized_start=421
  _PROGRAMBLUEPRINTDAOCONTAINERV1_PROGRAMBLUEPRINTSENTRY._serialized_end=539
  _PROGRAMBLUEPRINTDAOV1._serialized_start=564
  _PROGRAMBLUEPRINTDAOV1._serialized_end=773
# @@protoc_insertion_point(module_scope)
