# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/SharedItem.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.ProgramBlueprintDao import ProgramBlueprintDaoV1_pb2 as proto_dot_ProgramBlueprintDao_dot_ProgramBlueprintDaoV1__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16proto/SharedItem.proto\x12\x11LiftLog.Ui.Models\x1a\x35proto/ProgramBlueprintDao/ProgramBlueprintDaoV1.proto\"t\n\x11SharedItemPayload\x12T\n\x18shared_program_blueprint\x18\x01 \x01(\x0b\x32\x30.LiftLog.Ui.Models.SharedProgramBlueprintPayloadH\x00\x42\t\n\x07payload\"x\n\x1dSharedProgramBlueprintPayload\x12W\n\x11program_blueprint\x18\x01 \x01(\x0b\x32<.LiftLog.Ui.Models.ProgramBlueprintDao.ProgramBlueprintDaoV1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.SharedItem_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SHAREDITEMPAYLOAD._serialized_start=100
  _SHAREDITEMPAYLOAD._serialized_end=216
  _SHAREDPROGRAMBLUEPRINTPAYLOAD._serialized_start=218
  _SHAREDPROGRAMBLUEPRINTPAYLOAD._serialized_end=338
# @@protoc_insertion_point(module_scope)
