# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/UserEvent.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from proto.SessionHistoryDao import SessionHistoryDaoV2_pb2 as proto_dot_SessionHistoryDao_dot_SessionHistoryDaoV2__pb2
from proto import Utils_pb2 as proto_dot_Utils__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/UserEvent.proto\x12\x11LiftLog.Ui.Models\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x31proto/SessionHistoryDao/SessionHistoryDaoV2.proto\x1a\x11proto/Utils.proto\"\xb2\x01\n\x10UserEventPayload\x12>\n\x0fsession_payload\x18\x01 \x01(\x0b\x32#.LiftLog.Ui.Models.SessionUserEventH\x00\x12M\n\x17removed_session_payload\x18\x02 \x01(\x0b\x32*.LiftLog.Ui.Models.RemovedSessionUserEventH\x00\x42\x0f\n\revent_payload\"V\n\x10SessionUserEvent\x12\x42\n\x07session\x18\x01 \x01(\x0b\x32\x31.LiftLog.Ui.Models.SessionHistoryDao.SessionDaoV2\"I\n\x17RemovedSessionUserEvent\x12.\n\nsession_id\x18\x01 \x01(\x0b\x32\x1a.LiftLog.Ui.Models.UuidDao\"\xb3\x02\n\x0fInboxMessageDao\x12\x30\n\x0c\x66rom_user_id\x18\x01 \x01(\x0b\x32\x1a.LiftLog.Ui.Models.UuidDao\x12=\n\x0e\x66ollow_request\x18\x02 \x01(\x0b\x32#.LiftLog.Ui.Models.FollowRequestDaoH\x00\x12?\n\x0f\x66ollow_response\x18\x03 \x01(\x0b\x32$.LiftLog.Ui.Models.FollowResponseDaoH\x00\x12H\n\x15unfollow_notification\x18\x04 \x01(\x0b\x32\'.LiftLog.Ui.Models.UnFollowNotificationH\x00\x12\x11\n\tsignature\x18\x05 \x01(\x0c\x42\x11\n\x0fmessage_payload\"X\n\x10\x46ollowRequestDao\x12/\n\x04name\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValueH\x00\x88\x01\x01\x42\x07\n\x05_nameJ\x04\x08\x02\x10\x03J\x04\x08\x03\x10\x04\"\xab\x01\n\x11\x46ollowResponseDao\x12@\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x0b\x32,.LiftLog.Ui.Models.FollowResponseAcceptedDaoH\x00\x12@\n\x08rejected\x18\x02 \x01(\x0b\x32,.LiftLog.Ui.Models.FollowResponseRejectedDaoH\x00\x42\x12\n\x10response_payload\"C\n\x19\x46ollowResponseAcceptedDao\x12\x0f\n\x07\x61\x65s_key\x18\x01 \x01(\x0c\x12\x15\n\rfollow_secret\x18\x02 \x01(\t\"\x1b\n\x19\x46ollowResponseRejectedDao\"-\n\x14UnFollowNotification\x12\x15\n\rfollow_secret\x18\x01 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.UserEvent_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USEREVENTPAYLOAD._serialized_start=147
  _USEREVENTPAYLOAD._serialized_end=325
  _SESSIONUSEREVENT._serialized_start=327
  _SESSIONUSEREVENT._serialized_end=413
  _REMOVEDSESSIONUSEREVENT._serialized_start=415
  _REMOVEDSESSIONUSEREVENT._serialized_end=488
  _INBOXMESSAGEDAO._serialized_start=491
  _INBOXMESSAGEDAO._serialized_end=798
  _FOLLOWREQUESTDAO._serialized_start=800
  _FOLLOWREQUESTDAO._serialized_end=888
  _FOLLOWRESPONSEDAO._serialized_start=891
  _FOLLOWRESPONSEDAO._serialized_end=1062
  _FOLLOWRESPONSEACCEPTEDDAO._serialized_start=1064
  _FOLLOWRESPONSEACCEPTEDDAO._serialized_end=1131
  _FOLLOWRESPONSEREJECTEDDAO._serialized_start=1133
  _FOLLOWRESPONSEREJECTEDDAO._serialized_end=1160
  _UNFOLLOWNOTIFICATION._serialized_start=1162
  _UNFOLLOWNOTIFICATION._serialized_end=1207
# @@protoc_insertion_point(module_scope)
