# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/Utils.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/Utils.proto\x12\x11LiftLog.Ui.Models\"\x18\n\x07UuidDao\x12\r\n\x05value\x18\x01 \x01(\x0c\"7\n\x0b\x44\x61teOnlyDao\x12\x0c\n\x04year\x18\x01 \x01(\x05\x12\r\n\x05month\x18\x02 \x01(\x05\x12\x0b\n\x03\x64\x61y\x18\x03 \x01(\x05\",\n\x0c\x44\x65\x63imalValue\x12\r\n\x05units\x18\x01 \x01(\x03\x12\r\n\x05nanos\x18\x02 \x01(\x0f\"e\n\x0bTimeOnlyDao\x12\x0c\n\x04hour\x18\x01 \x01(\x05\x12\x0e\n\x06minute\x18\x02 \x01(\x05\x12\x0e\n\x06second\x18\x03 \x01(\x05\x12\x13\n\x0bmillisecond\x18\x04 \x01(\x05\x12\x13\n\x0bmicrosecond\x18\x05 \x01(\x05\"\xab\x01\n\x0b\x44\x61teTimeDao\x12,\n\x04\x64\x61te\x18\x01 \x01(\x0b\x32\x1e.LiftLog.Ui.Models.DateOnlyDao\x12,\n\x04time\x18\x02 \x01(\x0b\x32\x1e.LiftLog.Ui.Models.TimeOnlyDao\x12\x35\n\x06offset\x18\x03 \x01(\x0b\x32 .LiftLog.Ui.Models.ZoneOffsetDaoH\x00\x88\x01\x01\x42\t\n\x07_offset\"&\n\rZoneOffsetDao\x12\x15\n\rtotal_seconds\x18\x01 \x01(\x05\"e\n\x06Weight\x12.\n\x05value\x18\x01 \x01(\x0b\x32\x1f.LiftLog.Ui.Models.DecimalValue\x12+\n\x04unit\x18\x02 \x01(\x0e\x32\x1d.LiftLog.Ui.Models.WeightUnit*0\n\nWeightUnit\x12\x07\n\x03NIL\x10\x00\x12\r\n\tKILOGRAMS\x10\x01\x12\n\n\x06POUNDS\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.Utils_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WEIGHTUNIT._serialized_start=589
  _WEIGHTUNIT._serialized_end=637
  _UUIDDAO._serialized_start=40
  _UUIDDAO._serialized_end=64
  _DATEONLYDAO._serialized_start=66
  _DATEONLYDAO._serialized_end=121
  _DECIMALVALUE._serialized_start=123
  _DECIMALVALUE._serialized_end=167
  _TIMEONLYDAO._serialized_start=169
  _TIMEONLYDAO._serialized_end=270
  _DATETIMEDAO._serialized_start=273
  _DATETIMEDAO._serialized_end=444
  _ZONEOFFSETDAO._serialized_start=446
  _ZONEOFFSETDAO._serialized_end=484
  _WEIGHT._serialized_start=486
  _WEIGHT._serialized_end=587
# @@protoc_insertion_point(module_scope)
