# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/CurrentSessionStateDao/CurrentSessionStateDaoV2.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.SessionHistoryDao import SessionHistoryDaoV2_pb2 as proto_dot_SessionHistoryDao_dot_SessionHistoryDaoV2__pb2
from proto import Utils_pb2 as proto_dot_Utils__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;proto/CurrentSessionStateDao/CurrentSessionStateDaoV2.proto\x12(LiftLog.Ui.Models.CurrentSessionStateDao\x1a\x31proto/SessionHistoryDao/SessionHistoryDaoV2.proto\x1a\x11proto/Utils.proto\"\xea\x01\n\x18\x43urrentSessionStateDaoV2\x12O\n\x0fworkout_session\x18\x01 \x01(\x0b\x32\x31.LiftLog.Ui.Models.SessionHistoryDao.SessionDaoV2H\x00\x88\x01\x01\x12O\n\x0fhistory_session\x18\x02 \x01(\x0b\x32\x31.LiftLog.Ui.Models.SessionHistoryDao.SessionDaoV2H\x01\x88\x01\x01\x42\x12\n\x10_workout_sessionB\x12\n\x10_history_sessionJ\x04\x08\x03\x10\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.CurrentSessionStateDao.CurrentSessionStateDaoV2_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CURRENTSESSIONSTATEDAOV2._serialized_start=176
  _CURRENTSESSIONSTATEDAOV2._serialized_end=410
# @@protoc_insertion_point(module_scope)
